---
title: "Evaluation - Journey through R, A motivating workshop"
author: "Julius Fenn"
format:
  html:
    toc: true
    toc-depth: 3
    html-math-method: katex
---

```{r}
#| echo: false
#| warning: false

# sets the directory of location of this script as the current directory
# setwd(dirname(rstudioapi::getSourceEditorContext()$path))

### load packages
require(pacman)
p_load('tidyverse', 'jsonlite', 'magrittr', 'xlsx',
       'stargazer', 'psych', 'jtools', 'DT', 'ggstatsplot', 
       'lavaan', 
       'regsem', 'MplusAutomation')


### load data
#> JATOS file
setwd("data")
# dir()
suppressMessages(read_file('jatos_results_data_20240301084309.txt') %>%
  # ... split it into lines ...
  str_split('\n') %>% first() %>%
  # ... filter empty rows ...
  discard(function(x) x == '') %>%
  # ... parse JSON into a data.frame
  map_dfr(fromJSON, flatten=TRUE)) -> dat


### load functions
setwd("../functions")
for(i in 1:length(dir())){
  # print(dir()[i])
  source(dir()[i], encoding = "utf-8")
}
```

# prepare data

## set up data.frame

```{r}
### create counter variable
dat$ID <- NA
tmp_IDcounter <- 0
for(i in 1:nrow(dat)){
  if(!is.na(dat$meta.devicePixelRatio[i])){
    tmp_IDcounter = tmp_IDcounter + 1
  }
  dat$ID[i] <- tmp_IDcounter
}


### remove variables not necessary, keep only complete data sets
dat <- dat[, str_subset(string = colnames(dat), pattern = "^\\.\\.", negate = TRUE)]
sum(table(dat$ID) != max(table(dat$ID)))
sum(table(dat$ID) == max(table(dat$ID)))
dat <- dat[dat$ID %in% names(table(dat$ID))[table(dat$ID) == max(table(dat$ID))],]


### json (from JATOS) to 2D data.frame
# paradata
tmp_notNumeric <- str_subset(string = colnames(dat), pattern = "^meta|^R")
tmp_notNumeric <- str_subset(string = tmp_notNumeric, pattern = "labjs|location", negate = TRUE)

tmp_numeric <- str_subset(string = colnames(dat), pattern = "^lecturer|^workshop")


vec_ques <- c(tmp_notNumeric,
                tmp_numeric,
                "text_feedback")

vec_notNumeric = c(tmp_notNumeric,
                   "text_feedback")

questionnaire <- questionnairetype(dataset = dat, 
                                        listvars = vec_ques, 
                                        notNumeric = vec_notNumeric, verbose = FALSE)

vec_labels <- c("strongly disagree", "disagree", "neutral", "agree", "strongly agree")

questionnaire$`lecturer-technical` <- vec_labels[questionnaire$`lecturer-technical`]
questionnaire$`lecturer-technical` <- factor(questionnaire$`lecturer-technical`, levels = vec_labels)

questionnaire$`lecturer-complex` <- vec_labels[questionnaire$`lecturer-complex`]
questionnaire$`lecturer-complex` <- factor(questionnaire$`lecturer-complex`, levels = vec_labels)

questionnaire$`lecturer-prepared` <- vec_labels[questionnaire$`lecturer-prepared`]
questionnaire$`lecturer-prepared` <- factor(questionnaire$`lecturer-prepared`, levels = vec_labels)

questionnaire$`workshop-coverage` <- vec_labels[questionnaire$`workshop-coverage`]
questionnaire$`workshop-coverage` <- factor(questionnaire$`workshop-coverage`, levels = vec_labels)

questionnaire$`workshop-academiclife` <- vec_labels[questionnaire$`workshop-academiclife`]
questionnaire$`workshop-academiclife` <- factor(questionnaire$`workshop-academiclife`, levels = vec_labels)

questionnaire$`workshop-technical` <- vec_labels[questionnaire$`workshop-technical`]
questionnaire$`workshop-technical` <- factor(questionnaire$`workshop-technical`, levels = vec_labels)


vec_labels <- c("poor", "average", "good", "very good", "excellent")
questionnaire$`lecturer_overall-rating` <- vec_labels[questionnaire$`lecturer_overall-rating`]
questionnaire$`lecturer_overall-rating` <- factor(questionnaire$`lecturer_overall-rating`, levels = vec_labels)

questionnaire$`workshop_overall-rating` <- vec_labels[questionnaire$`workshop_overall-rating`]
questionnaire$`workshop_overall-rating` <- factor(questionnaire$`workshop_overall-rating`, levels = vec_labels)
```

# show evaluation

## Assessment of the lecturer

```{r, message = FALSE}
# Question:  The lecturer handled the technical equipment without problems. 
# > ranging from [1-5], "strongly disagree" to "strongly agree"
barplot(table(questionnaire$`lecturer-technical`))

# Question: The lecturer explained even complex topics in a comprehensible way.
barplot(table(questionnaire$`lecturer-complex`))

# Question: The lecturer was well prepared.
barplot(table(questionnaire$`lecturer-complex`))

# Question:  The lecturer was well prepared. 
barplot(table(questionnaire$`lecturer-prepared`))

## overall rating
# Question: Please grade the lecturer for this workshop.
barplot(table(questionnaire$`lecturer_overall-rating`))
```
## Assessment of the workshop


```{r, message = FALSE}
# Question:   The degree of content coverage of the topic was appropriate. 
# > ranging from [1-5], "strongly disagree" to "strongly agree"
barplot(table(questionnaire$`workshop-coverage`))

# Question:  The workshop optimally prepares me for my academic life. 
barplot(table(questionnaire$`workshop-academiclife`))

# Question:  The workshop focuses on the current professional discussions. 
barplot(table(questionnaire$`workshop-technical`))


## overall rating
# Question: Please grade the lecturer for this workshop.
barplot(table(questionnaire$`workshop_overall-rating`))
```

## Textual feedback

Any feedback or critic?

> Any critique or suggestions for improvement will help me a lot to make future workshops better. Positive criticism (if you have any) is also very welcome and will help to promote the workshop in the future. 

```{r, message = FALSE}
# Question: Do you have any feedback or critique regarding the workshop? 
DT::datatable(questionnaire[, c("ID","text_feedback")], options = list(pageLength = 5)) 
```
