---
title: "Basic Cocabulary"
author: "Julius Fenn"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    theme: united
    number_sections: true
---




```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# R Reference Card

See R Reference Card 2.0: https://cran.r-project.org/doc/contrib/Baggott-refcard-v2.pdf

and Cheatsheets in R:  https://posit.co/resources/cheatsheets/?type=posit-cheatsheets/


# Working with R

```{r, eval=FALSE}
# The first functions to learn
?
str
# Workspace
ls, exists, rm
getwd, setwd
q
source
install.packages, library, require
# Help
help, ?
help.search
apropos
RSiteSearch
citation
demo
example
vignette
```


# Basic Operations

```{r, eval=FALSE}
# Important operators and assignment
%in%, match
=, <-, <<-
$, [, [[, head, tail, subset
# Comparison
all.equal, identical
!=, ==, >, >=, <, <=
is.na, complete.cases
is.finite
# Basic math
*, +, -, /, ^, %%, %/%
abs, sign
acos, asin, atan, atan2
sin, cos, tan
ceiling, floor, round
exp, log, log10, log2, sqrt
max, min, prod, sum
cummax, cummin, cumprod, cumsum, diff
pmax, pmin
range
mean, median, cor, sd, var
# Functions to do with functions
function
missing
return, invisible
# Logical & sets
&, |, !, xor
all, any
intersect, union, setdiff, setequal
which
# Vectors and matrices
c, matrix
# automatic coercion rules character > numeric > logical
length, dim, ncol, nrow
cbind, rbind
names, colnames, rownames
t
diag
as.matrix, data.matrix
# Making vectors
c
rep, rep_len
seq, seq_len, seq_along
rev
sample
choose, factorial, combn
(is/as).(character/numeric/logical/...)
# Lists & data.frames
list, unlist
data.frame, as.data.frame
split
expand.grid
# Apply & friends
lapply, sapply, vapply
apply
tapply
replicate
```

# Common Data Structures

```{r, eval=FALSE}
# Date time
ISOdate, ISOdatetime, strftime, strptime, date
difftime
julian, months, quarters, weekdays
# Character manipulation
grep, agrep
gsub
strsplit
chartr
nchar
tolower, toupper
substr
paste
# Factors
factor, levels, nlevels
reorder, relevel
cut, findInterval
interaction
options(stringsAsFactors = FALSE)
```
